version: "3.8"

services:
  vitruvserver:
    container_name: vitruv-security-server
    # TODO: adjust version (tag)
    image: vitruvserver:vX.Y
    environment:
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - TLS_PASSWORD=${TLS_PASSWORD}
    ports:
      - "443:8443"
    restart: unless-stopped
    # TODO: adjust domain
    volumes:
      - /etc/letsencrypt/live/vitruv-server.org/fullchain.pem:/app/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/vitruv-server.org/privkey.pem:/app/certs/privkey.pem:ro