<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ascet" nsURI="http://vitruv.tools/reactionsparser/ascet" nsPrefix="ascet">
  <eClassifiers xsi:type="ecore:EClass" name="AscetModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//AscetTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AscetTask" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptTask" eSuperTypes="#//AscetTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicTask" eSuperTypes="#//AscetTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareTask" eSuperTypes="#//AscetTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeTableTask" eSuperTypes="#//AscetTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitTask" eSuperTypes="#//AscetTask"/>
</ecore:EPackage>